### ISSUE TITLE
add new subscriber and adding him to  lists?

### ISSUE THREAD

**Issue by derralf** [phpList/RestAPIclientSimpleExample#4]
How to add a subscriber to a list?
SubscriberController.php just adds a subscriber to the database but there doesn't seem to be a possibility to add the subscriber to lists.
Also no confirmation mail gets sent out.
What am I missing?

**Comment by xh3n1** [comment]
@derralf that's not supported yet in the REST API.
You can arise feature requests or report issues here: https://github.com/phplist/rest-api

**Comment by derralf** [comment]
@xh3n1 ok, I see you just added the same feature request a few days ago.
Do you know if the REST API supports to get detail information about a member yet? In the old API (which I never have used) there exists subscriberGetByEmail() which seems to do this?

**Comment by xh3n1** [comment]
@derralf I don't know about the old API, but afaik you can get information about members of a list. 
https://github.com/phpList/rest-api/blob/master/docs/Api/RestApi.apib#L228-L259
